version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
      - amd64
    goarm:
      - "6"
      - "7"
    flags:
      - -trimpath
    ldflags:
      - '-s -w -X main.version={{ .Version }}'
    binary: beacon-emitter

archives:
  - format: tar.gz
    name_template: >-
      '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

nfpms:
  - vendor:       Shohei Umetsu
    homepage:     "https://github.com/jo7oem/beacon-emitter"
    maintainer:   Shohei Umetsu
    description:  "Send to slack about IP address "
    license:      MIT
    section:      net
    priority:     extra

    file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

    formats:
      - rpm
      - deb

    bindir: /usr/bin
    contents:
      # main systemd unit
      - src: deploy/beacon-emitter.service
        dst: /lib/systemd/system/beacon-emitter.service
      # instance systemd unit
      - src: deploy/beacon-emitter@.service
        dst: /lib/systemd/system/beacon-emitter@.service
      # config sample
      - src: deploy/config.yml
        dst: /etc/beacon-emitter/config.yml

    scripts:
      postinstall:  deploy/postinstall.sh
      postremove:   deploy/postremove.sh


changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
