name: Release

on:
  push:
    tags:
      - "v*"
env:
  GO_VERSION: "1.21.6"

jobs:
     goreleaser:
       name: Create Release
       runs-on: ubuntu-latest
       env:
         BUILD_GPG_KEY: ${{ secrets.GPG_KEY }}
         NFPM_DEFAULT_RPM_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
         GPG_KEY_PATH: "build_key.gpg"
       steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up Go
           uses: actions/setup-go@v3
           with:
             go-version: ${{env.GO_VERSION}}

         - name: save gpg key
           run: echo "${BUILD_GPG_KEY}" | base64 -d > $GPG_KEY_PATH

         - name: Run GoReleaser
           uses: goreleaser/goreleaser-action@v4
           with:
             args: release
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

         - name: Clean up
           run: rm -f $GPG_KEY_PATH