name: Release

on:
  push:
    tags:
      - "v*"
env:
  GO_VERSION: "1.21.6"

jobs:
     goreleaser:
       name: Create Release
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Set up Go
           uses: actions/setup-go@v3
           with:
             go-version: ${{env.GO_VERSION}}

         - name: Run GoReleaser
           uses: goreleaser/goreleaser-action@v4
           with:
             args: release
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}